
// WinMMwaveOut.cpp

#include "stdafx.h"
#include "WinMMwaveOut.h"

#pragma comment (lib, "winmm.lib")

const DWORD CWinMMIO::LastErrorTab[] = {
	ERROR_SUCCESS,
	ERROR_FILE_NOT_FOUND,
	ERROR_OUTOFMEMORY,
	ERROR_ACCESS_DENIED,
	ERROR_ACCESS_DENIED,
	ERROR_ACCESS_DENIED,
	ERROR_ACCESS_DENIED,
	ERROR_ACCESS_DENIED,
	ERROR_ACCESS_DENIED,
	ERROR_BAD_FORMAT,
	ERROR_INVALID_ACCESS,
	ERROR_FILE_NOT_FOUND,
	ERROR_ACCESS_DENIED,
	ERROR_SHARING_VIOLATION,
	ERROR_UNEXP_NET_ERR,
	ERROR_SHARING_BUFFER_EXCEEDED,
	ERROR_BAD_FORMAT
};


